### ISSUE TITLE
Failing to parse SCUS_974.65

### ISSUE THREAD

**Issue by Dnawrkshp** [Longestboi/sndata-converter#1]
Hey thanks for making this tool. I'm trying to extract the sndata symbols from an elf and it is failing. Do you have any suggestions?

For reference, the elf I'm trying this on can be found here: https://cdn.discordapp.com/attachments/438760249990840328/837452728728682548/PS2_Ratchet_-_Deadlocked_USA_SCUS-97465_2005-09-13.7z

Thanks!

```
Traceback (most recent call last):
  File "Z:\Mods\PS2\Deadlocked\sndataconverter\sndata-converter.py", line 115, in <module>
    startOfSndata = parseSndataHeader().addr2offset(sndataAddrInt)
NameError: name 'sndataAddrInt' is not defined
```

**Comment by Dnawrkshp** [comment]
Looking deeper into it I don't think that elf has sndata symbols. Gonna close.

**Comment by Longestboi** [comment]
Looks like you are right, I'm not seeing any signs of sndata header sections in the binary.
